language: java
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2
notifications:
  slack:
    secure: JMisDlbY76AZeIQn/IUw0TyCR7A6x0FoazJ5BR5Fz0S+AU0peSgU9J3IaqYWzp7rv7eXOOCExLVwzXFNz9cXCREhbbg5yoaKIfV0nQvu03Rt1cwsFqAHP/3M7zwSS2cdw++hoX3ErNcJVt1rhZCQkbcc33LDwx8tJnfDOgZ5wAg5Z3iempp4Zig+IgtqoccI2hmefgoNY68hApfRDhHTpJHdQeCLeYtEA8UpNpLhKGBzTONVhjwyeJxCBVuY/9GIW8p6TceWbIPpPWE1hRtQgLLfTtz3LUAU1aMbTYFEEYnNfeAMdSqnyPqgehpUaoX4M/ep/cvb5NGtDz4ksQrIBdc578YAv/YXP9Q1cTk8A2DT7e7yYQWrgH2M+KyEPi/HYRE8fT2BjzecA9wbJhkeNGS/Zt02mzUb8WmitgstnFLac+ibyUtXwK27RN3zdbaIKjr2FtDHU2qbQ3m8TRJXi7UgeAFc5HAnJ0TyqGYw/FbCRDgEuW3gz3a8MZSJmxy4/JtrAxdLdsI3UyZtj0wXCqxuaJOyOOI11UCqlD16fzB0S0A12lqq6sAIkNbGPB7shJ5iMK5rtip6S1ssuRJ8XgTATT/XiNIBXYaRMXAzv0QCYTRrR2dQnIDT4pzsEsTS4T150Jl5SgD88QfXUyree2Qg7bRTvQwe9ruPsBWDUBs=
