---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: r2dbc/r2dbc-postgresql

inputs:
- name: r2dbc-postgresql
- name: r2dbc-spi-artifactory

outputs:
- name: r2dbc-postgresql-artifactory

caches:
- path: maven

run:
  path: r2dbc-postgresql/ci/build.sh
