---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: r2dbc/r2dbc-postgresql

inputs:
- name: r2dbc-postgresql

outputs:
- name: distribution-repository

caches:
- path: maven
- path: postgresql

run:
  path: r2dbc-postgresql/ci/build.sh
